# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(709, 200)
        Login.setMinimumSize(QtCore.QSize(520, 200))
        Login.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(700, 300))
        self.frame.setStyleSheet("QFrame#frame {\n"
"    background-color: rgb(44, 62, 80);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.usernameLineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.usernameLineEdit.setStyleSheet("QLineEdit#usernameLineEdit{\n"
"    border-bottom:  3px solid rgb(127, 140, 141);\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}")
        self.usernameLineEdit.setMaxLength(16)
        self.usernameLineEdit.setFrame(False)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout.addWidget(self.usernameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.passwordLineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.passwordLineEdit.setStyleSheet("QLineEdit#passwordLineEdit{\n"
"    border-bottom:  3px solid rgb(127, 140, 141);\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}")
        self.passwordLineEdit.setMaxLength(16)
        self.passwordLineEdit.setFrame(False)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout.addWidget(self.passwordLineEdit)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginButton = QtWidgets.QPushButton(self.frame_3)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginButton.setStyleSheet("QPushButton#loginButton {\n"
"    color: white;\n"
"    background-color: rgb(0, 175, 240);\n"
"    font-weight: 600;\n"
"    border-radius: 10px;\n"
"    width: 180px;\n"
"    height: 30px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton#loginButton:hover{\n"
"    cursor: pointer;\n"
"    background-color: rgb(26, 183, 234);\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QPushButton#loginButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-bottom: 3px;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_2.addWidget(self.loginButton)
        self.goToRegisterButton = QtWidgets.QPushButton(self.frame_3)
        self.goToRegisterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goToRegisterButton.setStyleSheet("QPushButton#goToRegisterButton {\n"
"    color: white;\n"
"    background-color: rgb(255, 87, 0);\n"
"    font-weight: 600;\n"
"    border-radius: 10px;\n"
"    width: 180px;\n"
"    height: 30px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton#goToRegisterButton:hover{\n"
"    cursor: pointer;\n"
"    background-color: rgb(255, 87, 0);\n"
"    opacity: 0.5;\n"
"}\n"
"QPushButton#goToRegisterButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-bottom: 3px;\n"
"}")
        self.goToRegisterButton.setFlat(True)
        self.goToRegisterButton.setObjectName("goToRegisterButton")
        self.verticalLayout_2.addWidget(self.goToRegisterButton)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_3.addWidget(self.frame)
        Login.setCentralWidget(self.centralwidget)
        self.actionClose = QtWidgets.QAction(Login)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.usernameLineEdit.setPlaceholderText(_translate("Login", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("Login", "Password"))
        self.loginButton.setText(_translate("Login", "Login"))
        self.goToRegisterButton.setText(_translate("Login", "No Account? Register here!"))
        self.actionClose.setText(_translate("Login", "Close"))
import ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
