# Form implementation generated from reading ui file 'c:\Users\julia\Documents\HS Worms\Fächer\GUI\hs_wo_gui_2023\frontend\Login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(700, 300)
        Login.setMinimumSize(QtCore.QSize(520, 200))
        Login.setMaximumSize(QtCore.QSize(700, 300))
        Login.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(700, 300))
        self.frame.setStyleSheet("QFrame#frame {\n"
"    background-color: rgb(44, 62, 80);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 30, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.frame_5)
        self.usernameLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.usernameLineEdit.setStyleSheet("QLineEdit#usernameLineEdit{\n"
"    border-bottom:  3px solid rgb(127, 140, 141);\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}")
        self.usernameLineEdit.setMaxLength(16)
        self.usernameLineEdit.setFrame(False)
        self.usernameLineEdit.setCursorPosition(0)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.horizontalLayout_3.addWidget(self.usernameLineEdit)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 30)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.frame_4)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.passwordLineEdit.setStyleSheet("QLineEdit#passwordLineEdit{\n"
"    border-bottom:  3px solid rgb(127, 140, 141);\n"
"    background-color: rgb(52, 73, 94);\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}")
        self.passwordLineEdit.setMaxLength(16)
        self.passwordLineEdit.setFrame(False)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout_3.addWidget(self.passwordLineEdit)
        self.showPasswordCheckBox = QtWidgets.QCheckBox(parent=self.frame_4)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.showPasswordCheckBox.setFont(font)
        self.showPasswordCheckBox.setStyleSheet("color: white;")
        self.showPasswordCheckBox.setObjectName("showPasswordCheckBox")
        self.verticalLayout_3.addWidget(self.showPasswordCheckBox)
        self.verticalLayout.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.loginButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginButton.setStyleSheet("QPushButton#loginButton {\n"
"    color: white;\n"
"    background-color: rgb(0, 175, 240);\n"
"    font-weight: 600;\n"
"    border-radius: 10px;\n"
"    width: 180px;\n"
"    height: 30px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton#loginButton:hover{\n"
"    cursor: pointer;\n"
"    background-color: rgb(26, 183, 234);\n"
"    opacity: 0.7;\n"
"}")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout_2.addWidget(self.loginButton)
        self.goToRegisterButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.goToRegisterButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.goToRegisterButton.setStyleSheet("QPushButton#goToRegisterButton {\n"
"    color: white;\n"
"    background-color: rgb(0, 175, 240);\n"
"    font-weight: 600;\n"
"    border-radius: 10px;\n"
"    width: 180px;\n"
"    height: 30px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton#goToRegisterButton:hover{\n"
"    cursor: pointer;\n"
"    background-color: rgb(26, 183, 234);\n"
"    opacity: 0.7;\n"
"}")
        self.goToRegisterButton.setFlat(True)
        self.goToRegisterButton.setObjectName("goToRegisterButton")
        self.verticalLayout_2.addWidget(self.goToRegisterButton)
        self.horizontalLayout.addWidget(self.frame_3)
        self.horizontalLayout_2.addWidget(self.frame)
        Login.setCentralWidget(self.centralwidget)
        self.actionClose = QtGui.QAction(parent=Login)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.usernameLineEdit.setPlaceholderText(_translate("Login", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("Login", "Password"))
        self.showPasswordCheckBox.setText(_translate("Login", "Show password"))
        self.loginButton.setText(_translate("Login", "Login"))
        self.goToRegisterButton.setText(_translate("Login", "Register here"))
        self.actionClose.setText(_translate("Login", "Close"))
