# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nutzerprofil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(278, 415))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(52, 73, 94);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setStyleSheet("QFrame#frame_4 {\n"
"    background-color: rgb(44, 62, 80);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("background-color: white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.home_Button = QtWidgets.QPushButton(self.frame_5)
        self.home_Button.setText("")
        self.home_Button.setObjectName("home_Button")
        self.horizontalLayout_9.addWidget(self.home_Button)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.horizontalLayout_8.addWidget(self.frame_5, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("background-color: white;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.budget_label = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.budget_label.setFont(font)
        self.budget_label.setObjectName("budget_label")
        self.horizontalLayout_10.addWidget(self.budget_label)
        self.acc_Button = QtWidgets.QPushButton(self.frame_6)
        self.acc_Button.setText("")
        self.acc_Button.setObjectName("acc_Button")
        self.horizontalLayout_10.addWidget(self.acc_Button)
        self.shopping_Button = QtWidgets.QPushButton(self.frame_6)
        self.shopping_Button.setText("")
        self.shopping_Button.setObjectName("shopping_Button")
        self.horizontalLayout_10.addWidget(self.shopping_Button)
        self.horizontalLayout_8.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QFrame#frame_3 {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border-radius: 15px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: rgb(0, 195, 0);\n"
"    padding: 5px;\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    max-width: 200px;\n"
"    max-height: 40px;\n"
"}\n"
"QPushButton#pushButton:hover {\n"
"    cursor: pointer;\n"
"    background-color: rgb(37, 211, 102);\n"
"}\n"
"QPushButton#pushButton:pressed {\n"
"    padding-left: 3px;\n"
"    padding-bottom: 3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.Logout = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Logout.setFont(font)
        self.Logout.setStyleSheet("QPushButton#Logout {\n"
"    background-color:rgb(231, 76, 60);\n"
"    padding: 5px;\n"
"    color: white;\n"
"    border-radius: 20px;\n"
"    max-width: 200px;\n"
"    max-height: 40px;\n"
"}\n"
"QPushButton#Logout:hover {\n"
"    cursor: pointer;\n"
"    background-color: rgb(230, 126, 34);\n"
"}\n"
"QPushButton#Logout:pressed {\n"
"    padding-left: 3px;\n"
"    padding-bottom: 3px;\n"
"}")
        self.Logout.setObjectName("Logout")
        self.horizontalLayout_6.addWidget(self.Logout)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("QFrame#frame_8 {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border-radius: 15px;\n"
"    margin-bottom: 5px;\n"
"    padding: 10px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginLabel = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.loginLabel.setObjectName("loginLabel")
        self.horizontalLayout.addWidget(self.loginLabel)
        self.loginStatusLabel = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.loginStatusLabel.setFont(font)
        self.loginStatusLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.loginStatusLabel.setObjectName("loginStatusLabel")
        self.horizontalLayout.addWidget(self.loginStatusLabel)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setStyleSheet("QFrame#frame_11 {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    margin-bottom: 5px;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.benutzernameLabel = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.benutzernameLabel.setFont(font)
        self.benutzernameLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.benutzernameLabel.setObjectName("benutzernameLabel")
        self.horizontalLayout_4.addWidget(self.benutzernameLabel)
        self.usernameLabel = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.usernameLabel.setObjectName("usernameLabel")
        self.horizontalLayout_4.addWidget(self.usernameLabel)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setStyleSheet("QFrame#frame_13 {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    margin-bottom: 5px;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.passwordLabel = QtWidgets.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.passwordLabel.setObjectName("passwordLabel")
        self.horizontalLayout_5.addWidget(self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("QLineEdit#passwordLineEdit {\n"
"    color: white;\n"
"    border-bottom: 3px solid rgb(189, 195, 199);\n"
"}")
        self.passwordLineEdit.setMaxLength(16)
        self.passwordLineEdit.setFrame(False)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.horizontalLayout_5.addWidget(self.passwordLineEdit)
        self.showPasswordCheckBox = QtWidgets.QCheckBox(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showPasswordCheckBox.setFont(font)
        self.showPasswordCheckBox.setStyleSheet("color: white;")
        self.showPasswordCheckBox.setObjectName("showPasswordCheckBox")
        self.horizontalLayout_5.addWidget(self.showPasswordCheckBox)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setStyleSheet("QFrame#frame_7 {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    margin-bottom: 5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 5px;")
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.budgetLineEdit = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.budgetLineEdit.setFont(font)
        self.budgetLineEdit.setStyleSheet("QLineEdit#budgetLineEdit {\n"
"    color: white;\n"
"    border-bottom: 3px solid rgb(189, 195, 199);\n"
"}")
        self.budgetLineEdit.setText("")
        self.budgetLineEdit.setMaxLength(9)
        self.budgetLineEdit.setFrame(False)
        self.budgetLineEdit.setObjectName("budgetLineEdit")
        self.horizontalLayout_7.addWidget(self.budgetLineEdit)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setStyleSheet("QFrame#frame_12 {\n"
"    background-color: rgb(44, 62, 80);\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.aenderungenVerwerfenButton = QtWidgets.QPushButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.aenderungenVerwerfenButton.setFont(font)
        self.aenderungenVerwerfenButton.setStyleSheet("QPushButton#aenderungenVerwerfenButton {\n"
"    color: white;\n"
"    padding: 5px 0px;\n"
"    background-color: rgb(255, 51, 0);\n"
"    max-height: 30px;\n"
"}")
        self.aenderungenVerwerfenButton.setObjectName("aenderungenVerwerfenButton")
        self.verticalLayout.addWidget(self.aenderungenVerwerfenButton)
        self.aenderungenSpeichernButton = QtWidgets.QPushButton(self.frame_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.aenderungenSpeichernButton.setFont(font)
        self.aenderungenSpeichernButton.setStyleSheet("QPushButton#aenderungenSpeichernButton {\n"
"    color: white;\n"
"    padding: 5px 0px;\n"
"    background-color: rgb(0, 153, 255);\n"
"    max-height: 30px;\n"
"}")
        self.aenderungenSpeichernButton.setObjectName("aenderungenSpeichernButton")
        self.verticalLayout.addWidget(self.aenderungenSpeichernButton)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(2, 8)
        self.verticalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nutzerprofil"))
        self.label_2.setText(_translate("MainWindow", "WEBSHOP.DE"))
        self.budget_label.setText(_translate("MainWindow", "Budget"))
        self.pushButton.setText(_translate("MainWindow", "Icon"))
        self.Logout.setText(_translate("MainWindow", "Logout / Change User"))
        self.loginLabel.setText(_translate("MainWindow", "Eingeloggt als:"))
        self.loginStatusLabel.setText(_translate("MainWindow", "loginStatus"))
        self.benutzernameLabel.setText(_translate("MainWindow", "Benutzername:"))
        self.usernameLabel.setText(_translate("MainWindow", "User"))
        self.passwordLabel.setText(_translate("MainWindow", "Passwort:"))
        self.passwordLineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.showPasswordCheckBox.setText(_translate("MainWindow", "Show password"))
        self.label.setText(_translate("MainWindow", "Budget:"))
        self.budgetLineEdit.setPlaceholderText(_translate("MainWindow", "Budget in €"))
        self.aenderungenVerwerfenButton.setText(_translate("MainWindow", "Änderungen verwerfen"))
        self.aenderungenSpeichernButton.setText(_translate("MainWindow", "Änderungen speichern"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
