# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/nhatlamluong/Projects/hs_wo_gui_2023/frontend/Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(340, 161)
        self.centralwidget = QtWidgets.QWidget(Register)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 338, 158))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.registerAsComboBox = QtWidgets.QComboBox(self.frame_2)
        self.registerAsComboBox.setObjectName("registerAsComboBox")
        self.registerAsComboBox.addItem("")
        self.registerAsComboBox.addItem("")
        self.registerAsComboBox.addItem("")
        self.registerAsComboBox.addItem("")
        self.verticalLayout_2.addWidget(self.registerAsComboBox)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.verticalLayout_2.addWidget(self.usernameLineEdit)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.verticalLayout_2.addWidget(self.passwordLineEdit)
        self.budgetLineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.budgetLineEdit.setText("")
        self.budgetLineEdit.setObjectName("budgetLineEdit")
        self.verticalLayout_2.addWidget(self.budgetLineEdit)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.registerButton = QtWidgets.QPushButton(self.frame)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)
        self.goToLoginButton = QtWidgets.QPushButton(self.frame)
        self.goToLoginButton.setAutoDefault(False)
        self.goToLoginButton.setDefault(False)
        self.goToLoginButton.setFlat(True)
        self.goToLoginButton.setObjectName("goToLoginButton")
        self.verticalLayout.addWidget(self.goToLoginButton)
        self.horizontalLayout.addWidget(self.frame)
        Register.setCentralWidget(self.centralwidget)
        self.actionClose = QtWidgets.QAction(Register)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(Register)
        self.registerAsComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.registerAsComboBox.setPlaceholderText(_translate("Register", "Register as..."))
        self.registerAsComboBox.setItemText(0, _translate("Register", "Please select profile..."))
        self.registerAsComboBox.setItemText(1, _translate("Register", "Käufer (Neuware)"))
        self.registerAsComboBox.setItemText(2, _translate("Register", "Käufer (Gebraucht)"))
        self.registerAsComboBox.setItemText(3, _translate("Register", "Verkäufer (Gebraucht)"))
        self.usernameLineEdit.setPlaceholderText(_translate("Register", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("Register", "Password"))
        self.budgetLineEdit.setPlaceholderText(_translate("Register", "Budget in €"))
        self.registerButton.setText(_translate("Register", "Register"))
        self.goToLoginButton.setText(_translate("Register", "Back to login!"))
        self.actionClose.setText(_translate("Register", "Close"))
