# Form implementation generated from reading ui file 'c:\Users\julia\Documents\HS Worms\Fächer\GUI\hs_wo_gui_2023\LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(660, 160)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.usernameLineEdit.setGeometry(QtCore.QRect(50, 20, 231, 31))
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(50, 50, 231, 31))
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.loginComboBox.setGeometry(QtCore.QRect(310, 30, 151, 31))
        self.loginComboBox.setObjectName("loginComboBox")
        self.loginComboBox.addItem("")
        self.loginComboBox.addItem("")
        self.loginComboBox.addItem("")
        self.loginComboBox.addItem("")
        self.loginButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(500, 20, 151, 61))
        self.loginButton.setObjectName("loginButton")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)
        self.actionClose = QtGui.QAction(parent=LoginWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "LoginWindow"))
        self.usernameLineEdit.setPlaceholderText(_translate("LoginWindow", "Username"))
        self.passwordLineEdit.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.loginComboBox.setPlaceholderText(_translate("LoginWindow", "Login as..."))
        self.loginComboBox.setItemText(0, _translate("LoginWindow", "Käufer Neuware"))
        self.loginComboBox.setItemText(1, _translate("LoginWindow", "Verkäufer Neuware"))
        self.loginComboBox.setItemText(2, _translate("LoginWindow", "Käufer Gebraucht"))
        self.loginComboBox.setItemText(3, _translate("LoginWindow", "Verkäufer Gebraucht"))
        self.loginButton.setText(_translate("LoginWindow", "Login"))
        self.menuFile.setTitle(_translate("LoginWindow", "File"))
        self.actionClose.setText(_translate("LoginWindow", "Close"))
